### ISSUE TITLE
thoughts

### ISSUE THREAD

**Issue by mattdesl** [stackgl/glsl-lighting-walkthrough#1]
some thoughts
- use ES5 instead of ES6 since GitHub cannot highlight it correctly :disappointed: 
- find ways of reducing some boilerplate with gl-geometry, simple shader, matrices, etc
  - some higher level _slightly more magical_ modules might be useful here
- this should focus mostly on GLSL. The JS to set things up should be as minimal as possible

**Comment by yoshuawuyts** [comment]
All sound good to me! Having some examples of how to do things correctly is definitely helpful for newcomers.

**Comment by mattdesl** [comment]
ok, the source is relatively clean now
